<!DOCTYPE html>
<html>
<head>
    <title>Export Devices - {{ now()->format('Y-m-d') }}</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: #16a34a;
            font-weight: bold;
        }
        .status-inactive {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .summary {
            background-color: #f0f9ff;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .summary h3 {
            margin: 0 0 10px 0;
            color: #1e40af;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Devices</h1>
        <p><strong>Tanggal Export:</strong> {{ now()->format('d F Y H:i:s') }}</p>
        <p><strong>Total Devices:</strong> {{ count($devices) }}</p>
    </div>

    <div class="summary">
        <h3>Ringkasan</h3>
        <p>
            <strong>Device Aktif:</strong> {{ $devices->where('is_active', true)->count() }} |
            <strong>Device Tidak Aktif:</strong> {{ $devices->where('is_active', false)->count() }}
        </p>
    </div>

    @if(count($devices) > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 8%">ID</th>
                    <th style="width: 25%">Nama Device</th>
                    <th style="width: 25%">Lokasi</th>
                    <th style="width: 12%">Status</th>
                    <th style="width: 15%">Valve State</th>
                    <th style="width: 15%">Dibuat</th>
                </tr>
            </thead>
            <tbody>
                @foreach($devices as $device)
                    <tr>
                        <td>{{ $device->id }}</td>
                        <td><strong>{{ $device->device_name ?? $device->name ?? '-' }}</strong></td>
                        <td>{{ $device->location ?? '-' }}</td>
                        <td class="{{ $device->is_active ? 'status-active' : 'status-inactive' }}">
                            {{ $device->is_active ? 'Aktif' : 'Tidak Aktif' }}
                        </td>
                        <td>{{ $device->valve_state ?? '-' }}</td>
                        <td>{{ \Carbon\Carbon::parse($device->created_at)->format('d/m/Y H:i') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #666;">
            <h3>Tidak ada data device</h3>
            <p>Belum ada device yang terdaftar dalam sistem.</p>
        </div>
    @endif

    <div class="footer">
        <p><strong>Smart Irrigation System</strong> | Generated by System Report</p>
        <p>© {{ now()->year }} - Export Devices Report</p>
    </div>
</body>
</html>