<!DOCTYPE html>
<html>
<head>
    <title>Export Sensor Data - {{ now()->format('Y-m-d') }}</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #059669;
            margin: 0;
            font-size: 22px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
            font-size: 9px;
        }
        th {
            background-color: #ecfdf5;
            font-weight: bold;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .summary {
            background-color: #ecfdf5;
            padding: 12px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
        .summary h3 {
            margin: 0 0 8px 0;
            color: #059669;
            font-size: 14px;
        }
        .warning {
            background-color: #fef3c7;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
            border-left: 4px solid #f59e0b;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Data Sensor</h1>
        <p><strong>Tanggal Export:</strong> {{ now()->format('d F Y H:i:s') }}</p>
        <p><strong>Total Records:</strong> {{ count($sensorData) }}</p>
    </div>

    @if(count($sensorData) >= 1000)
        <div class="warning">
            <strong>Peringatan:</strong> Data sensor dibatasi hingga 1,000 baris untuk PDF. Untuk data lengkap, gunakan export Excel.
        </div>
    @endif

    <div class="summary">
        <h3>📈 Statistik Data</h3>
        <p>
            <strong>Devices Unik:</strong> {{ $sensorData->pluck('device_name')->unique()->count() }} |
            <strong>Records Ditampilkan:</strong> {{ count($sensorData) }}
        </p>
    </div>

    @if(count($sensorData) > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 8%">ID</th>
                    <th style="width: 15%">Device</th>
                    <th style="width: 12%">Ground Temp (°C)</th>
                    <th style="width: 12%">Soil Moisture (%)</th>
                    <th style="width: 12%">Water Height (cm)</th>
                    <th style="width: 10%">Battery (V)</th>
                    <th style="width: 12%">Usage (L)</th>
                    <th style="width: 19%">Recorded At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sensorData as $data)
                    <tr>
                        <td>{{ $data->id }}</td>
                        <td><strong>{{ $data->device_name }}</strong></td>
                        <td class="text-right">{{ $data->ground_temperature_c ? number_format($data->ground_temperature_c, 1) : '-' }}</td>
                        <td class="text-right">{{ $data->soil_moisture_pct ? number_format($data->soil_moisture_pct, 1) : '-' }}</td>
                        <td class="text-right">{{ $data->water_height_cm ? number_format($data->water_height_cm, 1) : '-' }}</td>
                        <td class="text-right">{{ $data->battery_voltage_v ? number_format($data->battery_voltage_v, 2) : '-' }}</td>
                        <td class="text-right">{{ $data->irrigation_usage_total_l ? number_format($data->irrigation_usage_total_l, 2) : '-' }}</td>
                        <td>{{ \Carbon\Carbon::parse($data->recorded_at)->format('d/m/Y H:i:s') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #666;">
            <h3>Tidak ada data sensor</h3>
            <p>Belum ada data sensor yang tersedia dalam periode ini.</p>
        </div>
    @endif

    <div class="footer">
        <p><strong>Smart Irrigation System</strong> | Generated by System Report</p>
        <p>© {{ now()->year }} - Export Sensor Data Report (Limited to 1,000 rows for PDF)</p>
    </div>
</body>
</html>