<!DOCTYPE html>
<html>
<head>
    <title>Export Water Storages - {{ now()->format('Y-m-d') }}</title>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #0891b2;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f9ff;
            font-weight: bold;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: #16a34a;
            font-weight: bold;
        }
        .status-inactive {
            color: #dc2626;
            font-weight: bold;
        }
        .level-high {
            color: #16a34a;
            font-weight: bold;
        }
        .level-medium {
            color: #ca8a04;
            font-weight: bold;
        }
        .level-low {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .summary {
            background-color: #f0f9ff;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .summary h3 {
            margin: 0 0 10px 0;
            color: #0891b2;
        }
        .text-right {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Tangki Air</h1>
        <p><strong>Tanggal Export:</strong> {{ now()->format('d F Y H:i:s') }}</p>
        <p><strong>Total Tangki:</strong> {{ count($waterStorages) }}</p>
    </div>

    <div class="summary">
        <h3>Ringkasan</h3>
        <p>
            <strong>Tangki Normal:</strong> {{ $waterStorages->where('status', 'normal')->count() }} |
            <strong>Tangki Bermasalah:</strong> {{ $waterStorages->where('status', '!=', 'normal')->count() }} |
            <strong>Total Kapasitas:</strong> {{ number_format($waterStorages->sum('capacity_liters')) }} L
        </p>
    </div>

    @if(count($waterStorages) > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 8%">ID</th>
                    <th style="width: 20%">Nama Tangki</th>
                    <th style="width: 20%">Lokasi</th>
                    <th style="width: 15%">Kapasitas (L)</th>
                    <th style="width: 15%">Level Saat Ini (L)</th>
                    <th style="width: 10%">Persentase (%)</th>
                    <th style="width: 12%">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($waterStorages as $storage)
                    @php
                        $percentage = $storage->percentage ?? 0;
                        $levelClass = $percentage >= 70 ? 'level-high' : ($percentage >= 30 ? 'level-medium' : 'level-low');
                    @endphp
                    <tr>
                        <td>{{ $storage->id }}</td>
                        <td><strong>{{ $storage->tank_name ?? '-' }}</strong></td>
                        <td>{{ $storage->zone_name ?? $storage->area_name ?? '-' }}</td>
                        <td class="text-right">{{ number_format($storage->capacity_liters, 0) }}</td>
                        <td class="text-right">{{ number_format($storage->current_volume_liters, 0) }}</td>
                        <td class="text-right {{ $levelClass }}">{{ number_format($percentage, 1) }}%</td>
                        <td class="{{ $storage->status === 'normal' || $storage->status === 'active' ? 'status-active' : 'status-inactive' }}">
                            {{ ucfirst($storage->status ?? 'Unknown') }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #666;">
            <h3>Tidak ada data tangki air</h3>
            <p>Belum ada tangki air yang terdaftar dalam sistem.</p>
        </div>
    @endif

    <div class="footer">
        <p><strong>Smart Irrigation System</strong> | Generated by System Report</p>
        <p>© {{ now()->year }} - Export Water Storages Report</p>
    </div>
</body>
</html>